=== dl7vkj/jbidibc/trunk/jbidibc-simulation/src/main/resources/xsd/simulation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bidib.org/jbidibc/simulation/nodes" xmlns:sim="http://www.bidib.org/jbidibc/simulation/nodes" elementFormDefault="qualified" version="1.0">
	<simpleType name="String50Type">
		<restriction base="string">
			<minLength value="1"/>
			<maxLength value="50"/>
		</restriction>
	</simpleType>
	<simpleType name="StringNotEmptyType">
		<restriction base="string">
			<minLength value="1"/>
		</restriction>
	</simpleType>
	<simpleType name="UniqueIdType">
		<restriction base="hexBinary">
			<minLength value="7"/>
		</restriction>
	</simpleType>
	
	<complexType name="FeatureType">
		<attribute name="type" type="sim:String50Type" />
		<attribute name="value" type="int" />
	</complexType>
	
	<complexType name="FeaturesType">
		<sequence>
			<element name="feature" type="sim:FeatureType" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<complexType name="PortParamsType" abstract="true">
		<attribute name="portId" type="int" use="required" />
		<attribute name="dmxMapping" type="int" use="optional" default="0" />
		<attribute name="dimSlopeUp" type="int" use="optional" default="1" />
		<attribute name="dimSlopeDown" type="int" use="optional" default="1" />
		<attribute name="value" type="int" use="optional" default="0" />
	</complexType>
	<complexType name="BacklightPortParamsType">
		<complexContent>
			<extension base="sim:PortParamsType">
			</extension>
		</complexContent>
	</complexType>
	<complexType name="LightPortParamsType">
		<complexContent>
			<extension base="sim:PortParamsType">
				<attribute name="intensityOff" type="int" use="optional" default="0" />
				<attribute name="intensityOn" type="int" use="optional" default="0" />
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="PortType" abstract="true">
		<attribute name="count" type="int" />
	</complexType>
	<complexType name="BacklightPortType">
		<complexContent>
			<extension base="sim:PortType">
				<sequence>
					<element name="port" type="sim:BacklightPortParamsType" minOccurs="0" maxOccurs="unbounded" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="LightPortType">
		<complexContent>
			<extension base="sim:PortType">
				<sequence>
					<element name="port" type="sim:LightPortParamsType" minOccurs="0" maxOccurs="unbounded" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="SwitchPortType">
		<complexContent>
			<extension base="sim:PortType">
			</extension>
		</complexContent>
	</complexType>
	<complexType name="ServoPortType">
		<complexContent>
			<extension base="sim:PortType">
			</extension>
		</complexContent>
	</complexType>
	<complexType name="InputPortType">
		<complexContent>
			<extension base="sim:PortType">
			</extension>
		</complexContent>
	</complexType>

	<complexType name="DmxChannelParamsType">
		<attribute name="channelId" type="int" use="required" />
		<attribute name="initialState" type="int" use="required"/>
	</complexType>

	<complexType name="DmxChannelsType">
		<sequence>
			<element name="channel" type="sim:DmxChannelParamsType" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="count" type="int" />
	</complexType>

	<complexType name="NodeType">
		<sequence>
			<element name="BACKLIGHT" type="sim:BacklightPortType" minOccurs="0" />
			<element name="LPORT" type="sim:LightPortType" minOccurs="0" />
			<element name="SPORT" type="sim:SwitchPortType" minOccurs="0" />
			<element name="INPUT" type="sim:InputPortType" minOccurs="0" />
			<element name="SERVO" type="sim:ServoPortType" minOccurs="0" />
			<element name="DmxChannels" type="sim:DmxChannelsType" minOccurs="0" />
			<element name="Features" type="sim:FeaturesType" minOccurs="0" />
		</sequence>
		<attribute name="uniqueId" type="sim:UniqueIdType" use="required" />
		<attribute name="className" type="sim:StringNotEmptyType" use="required" />
		<attribute name="address" type="sim:StringNotEmptyType" use="required" />
		<attribute name="autoAddFeature" type="boolean" />
		<attribute name="productName" type="sim:String50Type" />
		<attribute name="userName" type="sim:String50Type" />
	</complexType>

	<complexType name="SubNodesType">
		<sequence>
			<element name="node" type="sim:NodeType" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="MasterType">
		<complexContent>
			<extension base="sim:NodeType">
				<sequence>
					<element name="subNodes" type="sim:SubNodesType" minOccurs="0" />
				</sequence>
<!-- 				<attribute name="uniqueId" type="hexBinary" /> --> 
			</extension>
		</complexContent>
	</complexType>

	<complexType name="HubType">
		<complexContent>
			<extension base="sim:NodeType">
				<sequence>
					<element name="subNodes" type="sim:SubNodesType" minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="simulation">
		<annotation>
			<documentation>Simulation configuration definition</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element name="master" type="sim:MasterType"/>
			</sequence>
		</complexType>
	</element>
	
</schema>

=== dl7vkj/jbidibc/trunk/jbidibc-simulation/src/test/resources/nodes/simulation.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns="http://www.bidib.org/jbidibc/simulation/nodes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bidib.org/jbidibc/simulation/nodes /xsd/simulation.xsd">
    <master uniqueId="d2000d680064ea" className="org.bidib.jbidibc.simulation.nodes.Master" address="0">
        <subNodes>
            <node uniqueId="05340d6B901234" className="org.bidib.jbidibc.simulation.nodes.Node" address="1" productName="Product1" userName="My username">
                <LPORT count="32"/>
                <SPORT count="8"/>
            </node>
            <node uniqueId="05343e97901235" className="org.bidib.jbidibc.simulation.nodes.Node" address="2" autoAddFeature="true">
                <SPORT count="8"/>
            </node>
            <node xsi:type="HubType" uniqueId="05343e97901236" className="org.bidib.jbidibc.simulation.nodes.Node" address="2">
                <INPUT count="8"/>
                <subNodes>
                    <node uniqueId="05343e97901237" className="org.bidib.jbidibc.simulation.nodes.Node" address="1">
                        <SPORT count="16"/>
                    </node>
                </subNodes>
            </node>
        </subNodes>
    </master>
</simulation>
