=== dl7vkj/jbidibc/trunk/jbidibc-exchange/src/main/resources/xsd/dmxsceneries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://www.bidib.org/jbidibc/dmxscenery"
	xmlns:dmxscenery="http://www.bidib.org/jbidibc/dmxscenery"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	targetNamespace="http://www.bidib.org/jbidibc/dmxscenery" 
	elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	
	<xsd:complexType name="DmxSceneryType">
		<xsd:sequence>
			<xsd:element ref="dmxChannel" maxOccurs="unbounded"/>
			<xsd:element ref="dmxSceneryPoints" minOccurs="0"/>
			<xsd:element ref="macroNumber" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="sceneryName" type="NameType" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="DmxSceneryPointsType">
		<xsd:sequence>
			<xsd:element ref="dmxSceneryPoint" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="DmxSceneryPointType">
		<xsd:sequence>
			<xsd:element ref="port" minOccurs="0" />
			<xsd:element name="dmxChannelNumber" type="ChannelNumberType" />
			<xsd:element name="macroNumber" type="MacroNumberType" minOccurs="0" />
			<xsd:element name="bidibAction" type="BidibActionType" minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="timeOffset" type="TimeOffsetType" use="required"/>
		<xsd:attribute name="brightness" type="BrightnessValueType" use="required"/>
		<xsd:attribute name="uniqueId" type="xsd:long" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="DmxChannelType">
		<xsd:sequence>
			<xsd:element ref="lineColor" minOccurs="0" />
			<xsd:element ref="port" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="channelNumber" type="ChannelNumberType" use="required"/>
		<xsd:attribute name="channelName" type="NameType"/>
	</xsd:complexType>

	<xsd:complexType abstract="true" name="PortType">
		<xsd:attribute name="portNumber" type="xsd:int" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="LightPortType">
		<xsd:complexContent>
			<xsd:extension base="PortType">
			</xsd:extension>
		</xsd:complexContent>		
	</xsd:complexType>
	
	<xsd:complexType name="BacklightPortType">
		<xsd:complexContent>
			<xsd:extension base="PortType">
			</xsd:extension>
		</xsd:complexContent>		
	</xsd:complexType>


	<xsd:complexType name="ColorType">
		<xsd:attribute name="red" type="ColorValueType" use="required"/>
		<xsd:attribute name="green" type="ColorValueType" use="required"/>
		<xsd:attribute name="blue" type="ColorValueType" use="required"/>
	</xsd:complexType>
		
	<xsd:simpleType name="NameType">
		<xsd:annotation>
			<xsd:documentation>The name of the scenery or DMX channel</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="50"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="ColorValueType">
		<xsd:annotation>
			<xsd:documentation>The color value</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="255"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="BrightnessValueType">
		<xsd:annotation>
			<xsd:documentation>The brightness value</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="255"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="TimeOffsetType">
		<xsd:annotation>
			<xsd:documentation>The time offset value</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="ChannelNumberType">
		<xsd:annotation>
			<xsd:documentation>The DMX channel number</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="64"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="MacroNumberType">
		<xsd:annotation>
			<xsd:documentation>The macro number</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="20"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="BidibActionType">
		<xsd:annotation>
			<xsd:documentation>The bidib action value</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="255"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="dmxSceneryPoint" type="DmxSceneryPointType"/>
	<xsd:element name="dmxSceneryPoints" type="DmxSceneryPointsType"/>
	<xsd:element name="dmxScenery" type="DmxSceneryType"/>
	<xsd:element name="dmxChannel" type="DmxChannelType"/>
	<xsd:element name="port" type="PortType"/>
	<xsd:element name="lineColor" type="ColorType"/>
	<xsd:element name="macroNumber" type="MacroNumberType"/>
	<xsd:element name="bidibAction" type="BidibActionType"/>

	<xsd:element name="dmxSceneries">
		<xsd:annotation>
			<xsd:documentation>DMX sceneries definition</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dmxscenery:dmxScenery" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== dl7vkj/jbidibc/trunk/jbidibc-exchange/src/test/resources/dmxscenery-test/dmxSceneries-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<dmxSceneries xmlns="http://www.bidib.org/jbidibc/dmxscenery" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="/xsd/dmxsceneries.xsd">
    <dmxScenery sceneryName="Scenery 1">
        <dmxChannel channelName="DMX Kanal 1" channelNumber="1">
            <lineColor red="255" green="55" blue="55"/>
            <port xsi:type="LightPortType" portNumber="1"/>
            <port xsi:type="LightPortType" portNumber="2"/>
            <port xsi:type="BacklightPortType" portNumber="1"/>
        </dmxChannel>
    </dmxScenery>
    <dmxScenery sceneryName="Scenery 2">
        <dmxChannel channelName="DMX Kanal 2" channelNumber="2">
            <lineColor red="55" green="55" blue="255"/>
            <port xsi:type="LightPortType" portNumber="1"/>
            <port xsi:type="LightPortType" portNumber="2"/>
            <port xsi:type="BacklightPortType" portNumber="0"/>
            <port xsi:type="BacklightPortType" portNumber="2"/>
        </dmxChannel>
        <dmxChannel channelName="DMX Kanal 3" channelNumber="3">
            <lineColor red="55" green="255" blue="55"/>
            <port xsi:type="LightPortType" portNumber="3"/>
            <port xsi:type="LightPortType" portNumber="4"/>
            <port xsi:type="BacklightPortType" portNumber="1"/>
            <port xsi:type="BacklightPortType" portNumber="2"/>
        </dmxChannel>
    </dmxScenery>
</dmxSceneries>
