=== dl7vkj/jbidibc/trunk/jbidibc-exchange/src/main/resources/xsd/vendor_cv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.bidib.org/jbidibc/vendorcv" xmlns:vendorcv="http://www.bidib.org/jbidibc/vendorcv" targetNamespace="http://www.bidib.org/jbidibc/vendorcv" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xsd:complexType name="VersionInfoType">
		<xsd:sequence>
			<xsd:any minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="Version" type="xsd:string" use="required"/>
		<xsd:attribute name="Versionm" type="xsd:string" use="optional"/>
		<xsd:attribute name="Lastupdate" type="xsd:string" use="required"/>
		<xsd:attribute name="Author" type="xsd:string" use="required"/>
		<xsd:attribute name="Pid" type="xsd:string" use="required"/>
		<xsd:attribute name="Vendor" type="xsd:string" use="required"/>
		<xsd:attribute name="Description" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="TemplateType">
		<xsd:sequence>
			<xsd:element name="CV" type="vendorcv:CVType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Node" type="vendorcv:NodeType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="Name" type="xsd:string" use="required"/>
		<xsd:attribute name="SkipOnTimeout" type="xsd:boolean" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="TemplatesType">
		<xsd:sequence>
			<xsd:element name="Template" type="vendorcv:TemplateType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CVType">
		<xsd:sequence>
			<xsd:element name="Description" type="vendorcv:DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Bitdescription" type="vendorcv:BitdescriptionType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="Number" type="xsd:int" use="required"/>
		<xsd:attribute name="Type" type="vendorcv:DataType" use="required"/>
		<xsd:attribute name="Min" type="xsd:string"/>
		<xsd:attribute name="Max" type="xsd:string"/>
		<xsd:attribute name="Low" type="xsd:string"/>
		<xsd:attribute name="High" type="xsd:string"/>
		<xsd:attribute name="Next" type="xsd:string"/>
		<xsd:attribute name="Values" type="xsd:string"/>
		<xsd:attribute name="Mode" type="vendorcv:ModeType" use="required"/>
		<xsd:attribute name="Rebootneeded" type="xsd:boolean" />
	</xsd:complexType>
	<xsd:complexType name="DescriptionType">
		<xsd:attribute name="Lang" type="xsd:string"/>
		<xsd:attribute name="Text" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="BitdescriptionType">
		<xsd:attribute name="Bitnum" type="xsd:int"/>
		<xsd:attribute name="Lang" type="xsd:string"/>
		<xsd:attribute name="Text" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="CVDefinitionType">
		<xsd:sequence>
			<xsd:element name="Node" type="vendorcv:NodeType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="DataType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Byte"/>
			<xsd:enumeration value="Int"/>
			<xsd:enumeration value="Bit"/>
			<xsd:enumeration value="DCC_ADDR_RG"/>
			<xsd:enumeration value="GBM16TReverser"/>
			<xsd:enumeration value="SignedChar"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ModeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="rw"/>
			<xsd:enumeration value="ro"/>
			<xsd:enumeration value="wo"/>
			<xsd:enumeration value="w"/>
			<xsd:enumeration value="h"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="VendorCV">
		<xsd:annotation>
			<xsd:documentation>VendorCV definition</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Version" type="vendorcv:VersionInfoType"/>
				<xsd:element name="Templates" type="vendorcv:TemplatesType" minOccurs="0"/>
				<xsd:element name="CVDefinition" type="vendorcv:CVDefinitionType" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="NodeType">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="Nodetext" type="vendorcv:NodetextType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Node" type="vendorcv:NodeType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="CV" type="vendorcv:CVType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="Offset" type="xsd:int"/>
		<xsd:attribute name="Template" type="xsd:string"/>
		<xsd:attribute name="Count" type="xsd:int" use="optional"/>
		<xsd:attribute name="Next" type="xsd:int" use="optional"/>
		<xsd:attribute name="Comment" type="xsd:string" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="NodetextType">
		<xsd:attribute name="Lang" type="xsd:string"/>
		<xsd:attribute name="Text" type="xsd:string"/>
	</xsd:complexType>
</xsd:schema>

=== dl7vkj/jbidibc/trunk/jbidibc-exchange/src/test/resources/bidib-test/BiDiBCV-13-115.xml
<?xml version="1.0" encoding="UTF-8"?>
<VendorCV xmlns="http://www.bidib.org/jbidibc/vendorcv" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bidib.org/jbidibc/vendorcv /xsd/vendor_cv.xsd">
    <Version Version="0.04" Versionm="441" Lastupdate="20140709" Author="Kufer, Wolfgang" Pid="115" Vendor="013" Description="OneDMX V1.0"/>
    <Templates>
        <Template Name="About">
            <CV Number="0" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="ro">
                <Description Lang="de-DE" Text="EEPROM Version"/>
                <Description Lang="en-EN" Text="EEPROM Version"/>
            </CV>
            <CV Number="1" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="ro">
                <Description Lang="de-DE" Text="Herstellerkennung"/>
                <Description Lang="en-EN" Text="Vendor ID"/>
            </CV>
            <CV Number="2" Type="Int" Min="-" Max="-" Low="2" High="3" Values="-" Mode="ro">
                <Description Lang="de-DE" Text="Produktkennung (low)"/>
                <Description Lang="en-EN" Text="ProductID (low)"/>
            </CV>
            <CV Number="3" Type="Int" Min="-" Max="-" Low="2" High="3" Values="-" Mode="ro">
                <Description Lang="de-DE" Text="Produktkennung (high)"/>
                <Description Lang="en-EN" Text="ProductID (high)"/>
            </CV>
            <CV Number="4" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="ro">
                <Description Lang="de-DE" Text="Firmware Version"/>
                <Description Lang="en-EN" Text="Firmware main version"/>
            </CV>
            <CV Number="5" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="ro">
                <Description Lang="de-DE" Text="Firmware Sub-Version"/>
                <Description Lang="en-EN" Text="Firmware sub version"/>
            </CV>
            <CV Number="6" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="ro">
                <Description Lang="de-DE" Text="Firmware Sub-Index"/>
                <Description Lang="en-EN" Text="Firmware compile run"/>
            </CV>
        </Template>
        <Template Name="DMX">
            <CV Number="0" Type="Byte" Min="-" Max="-" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="DMX: Startzustand"/>
                <Description Lang="en-EN" Text="DMX: init state"/>
            </CV>
        </Template>
        <Template Name="LightPort">
            <CV Number="0" Type="Byte" Min="0" Max="64" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Light-Port: DMX-Zielkanal (0..63), 64 = unbenutzt"/>
                <Description Lang="en-EN" Text="Light-Port: DMX target channel (0..63), 64 = not in use"/>
            </CV>
            <CV Number="1" Type="Byte" Min="-" Max="-" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Light-Port: Helligkeit für Zustand „aus“"/>
                <Description Lang="en-EN" Text="Light-Port: light intensity at status 'off'"/>
            </CV>
            <CV Number="2" Type="Byte" Min="-" Max="-" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Light-Port: Helligkeit für Zustand „an“"/>
                <Description Lang="en-EN" Text="Light-Port: light intensity at status 'on'"/>
            </CV>
            <CV Number="3" Type="Byte" Min="-" Max="-" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Light-Port: Dimmzeit in Richtung „aus“, 1 = langsam / 255 = schnell"/>
                <Description Lang="en-EN" Text="Light-Port: time to dim, direction 'off', 1 = slow / 255 = fast "/>
            </CV>
            <CV Number="4" Type="Byte" Min="-" Max="-" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Light-Port: Dimmzeit in Richtung „an“, 1 = langsam / 255 = schnell"/>
                <Description Lang="en-EN" Text="Light-Port: time to dim, direction 'on', 1 = slow / 255 = fast "/>
            </CV>
        </Template>
        <Template Name="Backlight">
            <CV Number="0" Type="Byte" Min="0" Max="64" Low="-" High="-" Values="-" Mode="ro">
                <Description Lang="de-DE" Text="Backlight: DMX-Zielkanal (0..63), 64 = unbenutzt"/>
                <Description Lang="en-EN" Text="Backlight: DMX target channel (0..63), 64 = not in use"/>
            </CV>
            <CV Number="1" Type="Byte" Min="-" Max="-" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Backlight: Dimmzeit in Richtung „aus“, 1 = langsam / 255 = schnell"/>
                <Description Lang="en-EN" Text="Backlight: time to dim, direction 'off', 1 = slow / 255 = fast "/>
            </CV>
            <CV Number="2" Type="Byte" Min="-" Max="-" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Backlight: Dimmzeit in Richtung „an“, 1 = langsam / 255 = schnell"/>
                <Description Lang="en-EN" Text="Backlight: time to dim, direction 'on', 1 = slow / 255 = fast "/>
            </CV>
            <CV Number="3" Type="Byte" Min="-" Max="-" Low="-" High="-" Values="-" Mode="ro">
                <Description Lang="de-DE" Text="Backlight: Reserviert"/>
                <Description Lang="en-EN" Text="Backlight: Reserved"/>
            </CV>
        </Template>
        <Template Name="AccessoryMap">
            <CV Number="0" Type="Byte" Min="0" Max="8" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Anzahl der möglichen Begriffe"/>
                <Description Lang="en-EN" Text="number of aspects"/>
            </CV>
            <CV Number="1" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Makro für Begriff 0"/>
                <Description Lang="en-EN" Text="macro for aspects 0"/>
            </CV>
            <CV Number="2" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Makro für Begriff 1"/>
                <Description Lang="en-EN" Text="macro for aspects 1"/>
            </CV>
            <CV Number="3" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Makro für Begriff 2"/>
                <Description Lang="en-EN" Text="macro for aspects 2"/>
            </CV>
            <CV Number="4" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Makro für Begriff 3"/>
                <Description Lang="en-EN" Text="macro for aspects 3"/>
            </CV>
            <CV Number="5" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Makro für Begriff 4"/>
                <Description Lang="en-EN" Text="macro for aspects 4"/>
            </CV>
            <CV Number="6" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Makro für Begriff 5"/>
                <Description Lang="en-EN" Text="macro for aspects 5"/>
            </CV>
            <CV Number="7" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Makro für Begriff 6"/>
                <Description Lang="en-EN" Text="macro for aspects 6"/>
            </CV>
            <CV Number="8" Type="Byte" Min="0" Max="255" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Makro für Begriff 7"/>
                <Description Lang="en-EN" Text="macro for aspects 7"/>
            </CV>
        </Template>
    </Templates>
    <CVDefinition>
        <Node Offset="1" Template="About">
            <Nodetext Lang="de-DE" Text="Allgemeine Daten"/>
            <Nodetext Lang="en-EN" Text="Common data"/>
        </Node>
        <Node>
            <Nodetext Lang="de-DE" Text="Konfiguration"/>
            <Nodetext Lang="en-EN" Text="Config"/>
            <CV Number="61" Type="Byte" Min="0" Max="1" Low="-" High="-" Values="-" Mode="rw">
                <Description Lang="de-DE" Text="Accessory beim Einschalten wieder herstellen"/>
                <Description Lang="en-EN" Text="Recover accessory aspect on power up"/>
            </CV>
            <Node>
                <Nodetext Lang="de-DE" Text="DMX-Kanäle"/>
                <Nodetext Lang="en-EN" Text="DMX-Channels"/>
                <Node Offset="71" Template="DMX" Count="64" Next="1">
                    <Nodetext Lang="de-DE" Text="DMX-Kanal %%p"/>
                    <Nodetext Lang="en-EN" Text="DMX-Channel %%p"/>
                </Node>
            </Node>
            <Node>
                <Nodetext Lang="de-DE" Text="Licht-Ports"/>
                <Nodetext Lang="en-EN" Text="Light ports"/>
                <Node Offset="135" Template="LightPort" Count="128" Next="5">
                    <Nodetext Lang="de-DE" Text="Licht-Port %%d"/>
                    <Nodetext Lang="en-EN" Text="Light port %%d"/>
                </Node>
            </Node>
            <Node>
                <Nodetext Lang="de-DE" Text="Backlight-Ports"/>
                <Nodetext Lang="en-EN" Text="Backlight ports"/>
                <Node Offset="775" Template="Backlight" Count="16" Next="4">
                    <Nodetext Lang="de-DE" Text="Backlight-Port %%d"/>
                    <Nodetext Lang="en-EN" Text="Backlight port %%d"/>
                </Node>
            </Node>
            <Node>
                <Nodetext Lang="de-DE" Text="Accessory"/>
                <Nodetext Lang="en-EN" Text="Accessory"/>
                <Node Offset="839" Template="AccessoryMap" Count="8" Next="9">
                    <Nodetext Lang="de-DE" Text="Accessory %%d"/>
